# Generated by Django 5.0.4 on 2024-05-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sweetness', models.CharField(choices=[('Dry', 'Dry'), ('Medium', 'Medium'), ('Sweet', 'Sweet')], default='Dry', max_length=20)),
                ('acidity', models.FloatField(default=0, verbose_name='Acidity')),
                ('alcohol', models.FloatField(default=0, verbose_name='Alcohol')),
                ('pH', models.FloatField(default=0, verbose_name='pH Value')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('type', models.CharField(default='Red', max_length=6, verbose_name='Type')),
                ('age', models.CharField(default='Non-vintage', max_length=12, verbose_name='Age')),
                ('image', models.ImageField(null=True, upload_to='wine_images/', verbose_name='Image')),
                ('winemaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Wine quantity')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wines.shoppingcart', verbose_name='Shopping Cart')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='wines.wine', verbose_name='Wine item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
                ('wines', models.ManyToManyField(to='wines.wine')),
            ],
        ),
    ]
