# Generated by Django 5.0.4 on 2024-04-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sweetness', models.CharField(choices=[('Dry', 'Dry'), ('Medium', 'Medium'), ('Sweet', 'Sweet')], max_length=20)),
                ('acidity', models.FloatField()),
                ('alcohol', models.FloatField()),
                ('pH', models.FloatField()),
                ('winemaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.winemaker')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('wines', models.ManyToManyField(to='wines.wine')),
            ],
        ),
    ]
