# Generated by Django 5.0.4 on 2024-05-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wines',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='wine',
            name='age',
            field=models.CharField(default='Non-vintage', max_length=12, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to='wine_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='wine',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(default='Red', max_length=6, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='acidity',
            field=models.FloatField(default=0, verbose_name='Acidity'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.FloatField(default=0, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='pH',
            field=models.FloatField(default=0, verbose_name='pH Value'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sweetness',
            field=models.CharField(choices=[('Dry', 'Dry'), ('Medium', 'Medium'), ('Sweet', 'Sweet')], default='Dry', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wines.order')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Wine quantity')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wines.shoppingcart', verbose_name='Shopping Cart')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='wines.wine', verbose_name='Wine item')),
            ],
        ),
    ]
