# Generated by Django 5.0.4 on 2024-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='age',
            field=models.CharField(default='Non-vintage', max_length=12, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='wine',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(default='Red', max_length=6, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='acidity',
            field=models.FloatField(default=0, verbose_name='Acidity'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.FloatField(default=0, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='pH',
            field=models.FloatField(default=0, verbose_name='pH Value'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sweetness',
            field=models.CharField(choices=[('Dry', 'Dry'), ('Medium', 'Medium'), ('Sweet', 'Sweet')], default='Dry', max_length=20),
        ),
    ]
