# Generated by Django 5.0.4 on 2024-05-25 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_is_allowing_notifications'),
        ('wines', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='customer')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine', verbose_name='wine')),
            ],
            options={
                'unique_together': {('customer', 'wine')},
            },
        ),
    ]
