# Generated by Django 5.0.4 on 2024-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_wine_age_wine_price_wine_quantity_wine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to='wine_images/', verbose_name='Image'),
        ),
    ]
