# Generated by Django 5.0.4 on 2024-05-14 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_shoppingcart_shoppingcartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wines',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wines.order')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine')),
            ],
        ),
    ]
