# Generated by Django 5.0.4 on 2024-05-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='manager',
        ),
    ]
