# Generated by Django 5.0.4 on 2024-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_allowing_notifications',
            field=models.BooleanField(default=False, verbose_name='is allowing notifications'),
        ),
    ]
