# Generated by Django 5.0.4 on 2024-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='street_number',
            field=models.IntegerField(default=0, verbose_name='Street Number'),
        ),
        migrations.AddField(
            model_name='winemaker',
            name='street_number',
            field=models.IntegerField(default=0, verbose_name='Street Number'),
        ),
    ]
