# Generated by Django 5.0.4 on 2024-04-16 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
    ]
