# Generated by Django 5.0.4 on 2024-05-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255, verbose_name='Driver Name')),
                ('capacity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('street_number', models.IntegerField(default=0, verbose_name='Street Number')),
                ('phone_number', models.CharField(max_length=20)),
                ('is_transporting', models.BooleanField(default=False)),
                ('is_operational', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(choices=[('scooter', 'Scooter'), ('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle')], max_length=20)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.city', verbose_name='City')),
            ],
        ),
    ]
