# Generated by Django 5.0.4 on 2024-04-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report'),
        ('vehicles', '0003_alter_vehicle_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.city', verbose_name='City'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
