# Generated by Django 5.0.4 on 2024-05-20 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineCellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WineTank',
            fields=[
                ('tank_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250, unique=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tank_type', models.CharField(choices=[('Inox', 'Inox'), ('Barrel', 'Barrel')], max_length=25)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_production.winecellar')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine')),
            ],
            options={
                'unique_together': {('tank_id', 'room')},
            },
        ),
        migrations.CreateModel(
            name='WineRacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racked_from', to='wine_production.winetank')),
                ('to_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racked_to', to='wine_production.winetank')),
            ],
        ),
    ]
