# Generated by Django 5.0.4 on 2024-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winetank',
            name='tank_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
