# Generated by Django 5.0.4 on 2024-05-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_production', '0002_alter_winetank_tank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winetank',
            name='tank_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WineRacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('from_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racked_from', to='wine_production.winetank')),
                ('to_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racked_to', to='wine_production.winetank')),
            ],
        ),
    ]
