# Generated by Django 5.0.4 on 2024-05-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wine_production', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermentationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine')),
                ('winemaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.winemaker')),
            ],
        ),
        migrations.CreateModel(
            name='FermentationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('sugar_level', models.FloatField()),
                ('pH', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='wine_production.fermentationbatch')),
            ],
        ),
    ]
