# Generated by Django 5.0.4 on 2024-05-08 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_production', '0003_alter_winetank_tank_id_wineracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wineracking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wineracking',
            name='time',
        ),
        migrations.AddField(
            model_name='wineracking',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
