# Generated by Django 5.0.4 on 2024-05-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_production', '0003_fermentationbatch_fermentationdata'),
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationbatch',
            name='estimated_completion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fermentationbatch',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='winetank',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.wine'),
        ),
    ]
