# Generated by Django 5.0.4 on 2024-05-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_production', '0004_fermentationbatch_estimated_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentationdata',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_production.fermentationbatch'),
        ),
    ]
